### ISSUE TITLE
Improve Accessibility 

### ISSUE THREAD

**Issue by fraserisland** [ryanditjia/gatsby-plugin-crisp-chat#2]
Are we able to target the crisp popup and add an aria-label attribute to it in this plugin? 

![Screen Shot 2019-06-20 at 6 25 45 am](https://user-images.githubusercontent.com/35257108/59798316-2aa46280-9325-11e9-9962-28ce50cc7e57.png)

**Comment by ryanditjia** [comment]
Hi Fraser, the plugin doesn’t have that feature. I believe it’s possible to tap into gatsby-browser API and do it imperatively, but it feels hacky.

Your best bet would be contacting Crisp so they can fix this for everyone, and not just Gatsby users 😃

**Comment by fraserisland** [comment]
Yeah, unfortunately that's the only way i think. I have tried to contact crisp but i don't think it would be a priority for them at the moment.
Would you be open to merging a PR if i made one doing this?

**Comment by ryanditjia** [comment]
PR would be great. Make sure it can be configured on or off though, with default being on.

**Comment by fraserisland** [comment]
@ryanditjia PR ready for your review!  👍
