### ISSUE TITLE
Trigger Opening of Chat box

### ISSUE THREAD

**Issue by kerematam** [ryanditjia/gatsby-plugin-crisp-chat#7]
I want my arbitrary button to trigger to open chat box. 

Is it possible?

**Comment by ryanditjia** [comment]
Not something that I’m familiar with. The plugin works the same way as Crisp’s official HTML implementation (but with some added accessibility and performance goodies). Perhaps ask Crisp if there’s a JS hook for that?

**Comment by kerematam** [comment]
For now, I have solved with this :   `document.querySelector('#crisp-chatbox > div > a').click()`

I will create issue there for a more proper way.

Thanks.
